services:
  nginx:
    ports:
      - "8080:80"

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: "${UID:-1000}"
        GROUP_ID: "${GID:-1000}"
    user: "${UID:-1000}:${GID:-1000}"

  phpmyadmin:
    ports:
      - 8081:80

# 標準の `docker-compose.yml` ではポートは固定されていません。
# 各自の環境で `docker-compose.override.yml` に以下のように記載してポートを割り当ててください。
