services:
  nginx:
    ports:
      - "8080:80"

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: "${UID:-1000}"
        GROUP_ID: "${GID:-1000}"
    user: "${UID:-1000}:${GID:-1000}"

  phpmyadmin:
    ports:
      - 8081:80